answer1 = int(input("Give a whole number that is greater than 4.\n-"))
print(answer1 > 4)
answer2 = int(input("Give a whole number that is less than 8.\n-"))
print(answer2 < 8)
answer3 = int(input("Give a whole number that is less than or equal to 5.\n-"))
print(answer3 <= 5)
answer4 = int(input("Give a whole number that is greater than or equal to 3.\n-"))
print(answer4 >= 3)
answer5 = int(input("Give a whole number that is equal to 7.\n-"))
print(answer5 == 7)
print("And Logical Operator:")
answer6 = int(input("Give a whole number that is greater than 6.\n-"))
answer7 = int(input("Give a whole number that is less than 4.\n-"))
print (answer6 > 6 and answer7 < 4)
print("Or Logical Operator:")
answer8 = int(input("Give a whole number that is greater than or equal to 8.\n-"))
answer9= int(input("Give a whole number that is less than or equal to 9.\n-"))
print(answer8 >= 8 or answer9<= 9)
print("Not Logical Operator")
answer10 = int(input("Give a whole number that is less than 10.\n-"))
answer11 = int(input("Give a whole number that is greater than 5.\n-"))
print (answer10 < 10 != answer11 > 5)
